{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-alpha02.aar",
          "url": "lifecycle-livedata-2.6.0-alpha02.aar",
          "size": 12324,
          "sha512": "499bdff19d6edfdc2c03cea47099292720068d7006ce3a1afe9d69d7fc95ddc56e33a77837b72661e50a17806036763faa90216f239c61ba425b4f73a76693b2",
          "sha256": "570c98eb983998ae5dc2156bac73cac646b34a16df53e7475a2b20fa7e3387a6",
          "sha1": "3415026053657c140915ad4c022d7c3c2af220f4",
          "md5": "7a8c9cde118c9f66da3adeadb0d8df72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "{androidx.LibraryVersions.LIFECYCLE}"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-alpha02.aar",
          "url": "lifecycle-livedata-2.6.0-alpha02.aar",
          "size": 12324,
          "sha512": "499bdff19d6edfdc2c03cea47099292720068d7006ce3a1afe9d69d7fc95ddc56e33a77837b72661e50a17806036763faa90216f239c61ba425b4f73a76693b2",
          "sha256": "570c98eb983998ae5dc2156bac73cac646b34a16df53e7475a2b20fa7e3387a6",
          "sha1": "3415026053657c140915ad4c022d7c3c2af220f4",
          "md5": "7a8c9cde118c9f66da3adeadb0d8df72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.6.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-2.6.0-alpha02-sources.jar",
          "size": 6922,
          "sha512": "3a61fb8d21edfc681dac588b7e14e81e752f0d43b6ede8324fc64ea23673519ce79a9e5c974cf0bf02eee990017538eccb92b690576468df834336804d4569f7",
          "sha256": "b9625574ea429ba49fa5d598e8f52914f7db54a52061460875b5decda9a295af",
          "sha1": "2ab5b2a10c95f8f8d5b061e42d2a176eee5d218e",
          "md5": "cfa10b562f680ea68be4bada7fd77e8d"
        }
      ]
    }
  ]
}