{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.2.0.aar",
          "url": "sqlite-framework-2.2.0.aar",
          "size": 12886,
          "sha512": "b4d1035e396175b571193d1afcce2a4ac6af1da9f9f33483cf68c1e6ab80eafac9e06e5f98cf604d7f094c73ac84f8605fa6bf887d27dce8a952f6937b91bbb5",
          "sha256": "e5f5fbe7c209e21cde21d1d781481c9b0245839bc03bdd89fa4a798945bdb6a5",
          "sha1": "d03400d2f8c716916ed4126ec9e52bdf1495c718",
          "md5": "2a50f9896bf2f24ba09bcbf01ef5ce99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.2.0.aar",
          "url": "sqlite-framework-2.2.0.aar",
          "size": 12886,
          "sha512": "b4d1035e396175b571193d1afcce2a4ac6af1da9f9f33483cf68c1e6ab80eafac9e06e5f98cf604d7f094c73ac84f8605fa6bf887d27dce8a952f6937b91bbb5",
          "sha256": "e5f5fbe7c209e21cde21d1d781481c9b0245839bc03bdd89fa4a798945bdb6a5",
          "sha1": "d03400d2f8c716916ed4126ec9e52bdf1495c718",
          "md5": "2a50f9896bf2f24ba09bcbf01ef5ce99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-framework-2.2.0-sources.jar",
          "url": "sqlite-framework-2.2.0-sources.jar",
          "size": 8456,
          "sha512": "e5ca2b2f1a4dcafaac5a88eff6a18a7c067e3cb4b7659b3271a45b52a40da189be8f668991b23ece1e965103c93bc582e0b53a59a9ad0bc5264aa0577f5bc06b",
          "sha256": "11d87175808c1e4de14fcdd3b44ef37d95f242ba16836b136d88654be9d3f3c3",
          "sha1": "276e5b579e93de6c6d9474d33d0e622cd35bf9e7",
          "md5": "2ebd102b7e5757772869b2c07707e71c"
        }
      ]
    }
  ]
}
