{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "room-migration-2.4.3.jar",
          "url": "room-migration-2.4.3.jar",
          "size": 22870,
          "sha512": "f5b1763fc5ee8165c4802514cb97d920dc81b108ae3b958536139eabc7d9119bb6fa0e96a8dc5479f46f9bc546851ff4ac29c19a070e5eb8c22c2a6405633f76",
          "sha256": "e0efe1ed8557f82628bfcb0b2058a5125472dcf31ef9af85c646d7eaaf900d20",
          "sha1": "3f681427593343d0b296b8fccc117569184f96f7",
          "md5": "541ada64e9a19dcf29f0e9370b1dd309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-migration-2.4.3.jar",
          "url": "room-migration-2.4.3.jar",
          "size": 22870,
          "sha512": "f5b1763fc5ee8165c4802514cb97d920dc81b108ae3b958536139eabc7d9119bb6fa0e96a8dc5479f46f9bc546851ff4ac29c19a070e5eb8c22c2a6405633f76",
          "sha256": "e0efe1ed8557f82628bfcb0b2058a5125472dcf31ef9af85c646d7eaaf900d20",
          "sha1": "3f681427593343d0b296b8fccc117569184f96f7",
          "md5": "541ada64e9a19dcf29f0e9370b1dd309"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-migration-2.4.3-sources.jar",
          "url": "room-migration-2.4.3-sources.jar",
          "size": 17964,
          "sha512": "33151e5bb97535f2bb814f52593da75a5cfcb262e712b1816949c118af6cac3a4e880a641bbb63db912027e8d7bb0899ca521acf993aae87fbd0ead709ccbf96",
          "sha256": "52ccf8ec797e505399fbd18278368ad52e24f2957020895054162c06956165f7",
          "sha1": "9b3768c509ccbc057556c10b3c4f7cb16c6bce7d",
          "md5": "ca846ca0be19add8f90f480ced8d723f"
        }
      ]
    }
  ]
}
