{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.3.jar",
          "url": "room-compiler-processing-2.4.3.jar",
          "size": 892291,
          "sha512": "f333da3137a1e94b8363bb249e463cbbcf489813c193cda3efc84342949a2cc2c49652e470b8821a0381d662cd684682b4d1034c3f5c269c0c645be4988ac1e3",
          "sha256": "1d7d5967c04ca082303c81ed41ce9d731269ff72fc62de64cb05e180efb38244",
          "sha1": "94deadc9e79a375f6ad45494fada38e1915783de",
          "md5": "cf948714b8c2573856ce14239d21dc96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.0-1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.3.jar",
          "url": "room-compiler-processing-2.4.3.jar",
          "size": 892291,
          "sha512": "f333da3137a1e94b8363bb249e463cbbcf489813c193cda3efc84342949a2cc2c49652e470b8821a0381d662cd684682b4d1034c3f5c269c0c645be4988ac1e3",
          "sha256": "1d7d5967c04ca082303c81ed41ce9d731269ff72fc62de64cb05e180efb38244",
          "sha1": "94deadc9e79a375f6ad45494fada38e1915783de",
          "md5": "cf948714b8c2573856ce14239d21dc96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.4.3-sources.jar",
          "url": "room-compiler-processing-2.4.3-sources.jar",
          "size": 188493,
          "sha512": "d86bd47dff3c7a11079d40426fcc8db146bcd73ccedbc3c97511412099c3bdf0c1577b45ba929bf6b0f1f8c8a5ca4c9004810d17d6c967fa8f319c7f2bc669ab",
          "sha256": "e285b79fd87c2ff0d32fe20f349e642b923c6dd3f2426c8b87b39f198cc427b2",
          "sha1": "491965fea45c14ab6af8fa60fb2d7b2e5eb6167e",
          "md5": "115e5308f3d48b64e1ea8d1f52ab4c19"
        }
      ]
    }
  ]
}
