{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha02.aar",
          "url": "lifecycle-livedata-core-2.6.0-alpha02.aar",
          "size": 10811,
          "sha512": "12e5ab0ced04b0e38baf2d7811acadb790d36f9f611b6df888d81db8bd83927218ec3bb7b1279467b65cf47b93ebca1ef721bb61cb7f059460e4ef739bfa629b",
          "sha256": "06aae822bdb1bf008a86d474374b799706caeefb5c57b089e41e9530a67a6b89",
          "sha1": "14ae17012e6ee6e650f62d184add8b47f84b79c7",
          "md5": "cff2c7d7137f44a770fe956475281896"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "{androidx.LibraryVersions.LIFECYCLE}"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "{androidx.LibraryVersions.LIFECYCLE}"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha02.aar",
          "url": "lifecycle-livedata-core-2.6.0-alpha02.aar",
          "size": 10811,
          "sha512": "12e5ab0ced04b0e38baf2d7811acadb790d36f9f611b6df888d81db8bd83927218ec3bb7b1279467b65cf47b93ebca1ef721bb61cb7f059460e4ef739bfa629b",
          "sha256": "06aae822bdb1bf008a86d474374b799706caeefb5c57b089e41e9530a67a6b89",
          "sha1": "14ae17012e6ee6e650f62d184add8b47f84b79c7",
          "md5": "cff2c7d7137f44a770fe956475281896"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.6.0-alpha02-sources.jar",
          "url": "lifecycle-livedata-core-2.6.0-alpha02-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}